import { LocaleRouteNormalizer } from "next/dist/server/future/normalizers/locale-route-normalizer"

export const englishLanguage = {
    realtimefuelmanagementsystem:'The real-time fuel management website is currently operational, with hundreds of users and fuel station companies, actively monitoring it. On the default website, 10 stations are running, providing detailed sales information. Many managers use this website for their stations to generate daily reports, manage accounts, and check profits and other staff details from their individual dashboards. The website maintains daily data directly sourced from the table application used by sellers and dispensers. Future plans include displaying information for 100 stations, allowing control of multiple accounts.',
    possetup: 'The POS setup website serves as an installer platform, widely utilized by installers to configure POS servers for various stations. Dispensers, nozzles, initial data, and account controls all originate from this POS setup web. Emphasizing simplicity, ease of use, and lightweight design, I aim to make the setup process straightforward for users, offering a plug-and-play experience through installers. This setup web has successfully configured 10 stations with ease. I designed it using Figma and developed it using React.js, Redux, React Router Dom, and Framermotion. Git and GitHub are utilized for version control.',
    ecommerce: 'The UI for this ecommerce website is ready for interaction with the API that I developed during my free time. The features include displaying products based on categories, special products, sale products, and popular products determined by user preferences. Additionally, there will be a blog section for advertising. On the products page, users can utilize filters based on prices, categories, color, and stock availability. The account management system records customer data. This ecommerce platform will have an active CMS admin dashboard via a Node.js server. The dashboard allows for the addition and removal of products and checking the status of customer accounts. I developed this ecommerce site using React.js, Redux, React Router Dom, and Redux Thunk. Git and GitHub are employed for version control.',
    bot: "ForeverBot is one of my projects developed with vanilla JavaScript. It showcases how I can build a website using pure JavaScript. It is a simple NFT web project.",
    drewhouse:"Drew House is my pure vanilla e-commerce website. It was a challenging frontend project at that time. I'm proud that it is currently running smoothly without any issues.",
    fmsapplication: 'The FMS application is currently operational across nine stations in Natogyi, Ohn Chaw, Kyawe Tat Sone, Kyein Pin Sel, Nawng Kio, Muse, Sittwe, Gwa, and Taunggyi. Fuel station employees are using this application with satisfaction, utilizing it to permit dispensers and adjust dispenser prices. They frequently use the app to monitor the fuel balance in the tanks.The application features two modes: auto permit and default permit. In auto permit mode, employees can add car numbers and customer information without requiring manual permission. Real-time dispenser counts are displayed within the application. If a dispenser is not connected or malfunctions, a notification will appear in the application.'
,
    ecommerceapi: 'For API development, I created a REST API using Node.js, Express, and MongoDB. This ecommerce API is designed with the MVC control pattern, a significant pattern for maintaining and identifying errors. I implemented thorough error handling to ensure the stability of the API and prevent crashes. Multiple middlewares are utilized for enhanced functionality.To efficiently handle images and videos, I integrated Cloudinary to store these media files, ensuring optimal API performance. The API includes a password recovery feature with email recovery and password reset functionalities, and I implemented Jsonweb token for security measures.For comprehensive API documentation, I utilized Swagger, providing a clear and accessible guide for users and developers alike.',
    youtube: 'YouTube Rest API is implemented using the MVC pattern with Node.js and MongoDB. I utilize Zod for type validation, JSON Web Token for account control and security, and TypeScript for robust development, incorporating multiple middlewares. To enhance resilience, I implement various error-handling mechanisms. MongoDB is employed as the database.',
    blog: 'This is a blog API project implementing the MVC pattern with MongoDB. It is based on CRUD operations with account control and API documentation using Swagger. For type validation, I utilize Zod.',
    microservice:'This is my current development state API with Microservices architecture using an API gateway. It runs an e-commerce API across four servers, each handling its specific processes. The Microservices architecture ensures that if one server is down, other servers can continue their processes seamlessly, providing users with a smooth web experience. For communication between the four servers, I employ a messaging protocol to push products to carts. In the development process, I use Express.js, Node.js, TypeScript, Zod, and JSON Web Token, with four MongoDB databases. I am currently actively working on it.',
    hobby:'I learned to connect my web and hardware devices for further improvement in my development. I am familiar with SSH technology, Raspbian OS, Linux, and server logic. Similar configurations apply to the Banana Pi. The server logic is the same as on a cloud server, such as EC2. Additionally, for the POS handler, I developed a printing application on Android, which proves to be highly beneficial for POS software.'
}

